<h1><?php echo $this->headerText?></h1>
<?php if($this->warningMessage):?><div class="message error closeable"><p><?php echo $this->warningMessage;?></p></div><?php endif;?>
<div align="right"><input type="button"
	onclick="location.href='<?php
	echo $this->url ( array ('controller' => 'categoria', 'module'=>'admin' ), 'default', true )?>'"
	class="button" value="Voltar"></input></div>
<div style="float:left;width: 400px;">
<?php
echo $this->form;
?>
</div>