<h1>Listagem de categorias</h1>
<?php
if ($this->sucessMessage) :
	?><div class="message success closeable">
<p><?php
	echo $this->sucessMessage;
	?></p>
</div>
<?php endif;
?>
<?php

if ($this->warningMessage) :
	?><div class="message error closeable">
<p><?php
	echo $this->warningMessage;
	?></p>
</div>
<?php endif;
?>
<div align="right"><input type="button"
	onclick="location.href='<?php
	echo $this->url ( array ('controller' => 'categoria', 'action' => 'incluir', 'module'=>'admin' ), 'default', true )?>'"
	class="button" value="Nova categoria"></input></div>
<table width="100%" cellpadding="0" cellspacing="0" border="0">
	<tr>
		<th width="800px">Nome</th>
		<th>Ações</th>
	</tr>
<?php
$class ='alt';
if($this->entries):
foreach ( $this->entries as $entry ) :
	if($class=='alt')
				$class='';
			else
				$class='alt';

	?>
  <tr>
		<td><?php
	echo $entry->getNome();
	?></td>
		<td><input type="button"
			onclick="location.href='<?php 
	echo $this->url ( array ('controller' => 'categoria', 'action' => 'incluir', 'module'=>'admin', 'id' => $entry->getIdCategoria () ), 'default', true )?>'"
			class="button" value="Alterar"></input> <input type="button"
			onclick="location.href='<?php
	echo $this->url ( array ('controller' => 'categoria', 'module'=>'admin', 'id' => $entry->getIdCategoria () ), 'default', true )?>'"
			class="button" value="Excluir"></input></td>
	</tr>
<?php
endforeach;
endif;
?>
</table>
<?php echo $this->paginationControl($this->entries, 'Sliding', 'pagination.phtml'); ?>