<h2><?php echo $this->headerText?>
<input type="button" id="voltar" onclick="location.href='<?php echo $this->url ( array ('controller' => 'modulo', 'module'=>'admin' ), 'default', true )?>'"	class="button" value="Voltar"></input>
</h2>
<?php if($this->warningMessage):?><div class="message error closeable"><p><?php echo $this->warningMessage;?></p></div><?php endif;?>
<table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr><td width="50%">
<?php
echo $this->form;
?></td>
<td width="50%">
<?php for($i=1;$i<15;$i++): ?>
<div class="modulo_icon button<?=$i?>">
	<span class="dashboard_button_heading"><?=$i?></span>
</div>
<?php endfor; ?>
</td>
</tr>
</table>