<h2>Listagem de usuários</h2>
<div align="right">
	<?php echo $this->ActionButton('usuario','incluir','admin','Cadastrar');?>
</div>
<br />
<table width="100%" cellpadding="0" cellspacing="0" border="0"
	id="table_liquid">
	<caption>Listagem de usuários cadastrados com autorização no sistema.</caption>
	<tr>
		<th width="450px">Usuário</th>
		<th width="240px">E-Mail</th>
		<th>Login</th>
		<th>Ações</th>
	</tr>
<?php
$class = 'alt';
if ($this->entries) :
	foreach ($this->entries->getCurrentItems() as $entry) :
		if ($class == 'alt')
			$class = '';
		else
			$class = 'alt';
		?>
  <tr>
		<th class="spec<?php
		echo $class;
		?>"><?php
		echo $entry['nome'];
		?></th>
		<td class="<?php
		echo $class;
		?>"><?php
		echo $entry['email'];
		?></td>
		<td class="<?php
		echo $class;
		?>"><?php
		echo $entry['login'];
		?></td>
		<td align="center" class="<?php
		echo $class;
		?>">
		<?php
		echo $this->ActionButton('usuario','alterar','admin','Alterar',array('id'=> $entry['idUsuario'])).' '; 
		echo $this->ActionButton('usuario','excluir','admin','Excluir',array('id'=> $entry['idUsuario']));
		?> 
		</td>
	</tr>
<?php
	endforeach;
	endif;
?>
</table>
<?php echo $this->paginationControl($this->entries, 'Sliding', 'pagination.phtml'); ?>