<h2><?php echo $this->headerText?>
<input type="button" id="voltar" onclick="location.href='<?php echo $this->url ( array ('controller' => 'foto', 'module'=>'admin' ), 'default', true )?>'"	class="button" value="Voltar"></input>
</h2>
<div style="float: left; width: 60%;">
<?php echo $this->form;?>
</div>
<div style="float: left; width: 40%;" align="center">
	<img src="<?php echo $this->baseUrl();?>/media/imagens/fotos/<?=$this->imagem?>"/>
</div>