<div id="backgroudConteudo"  style="background:<?php echo Zend_Registry::get('backgroudMeio'); ?>;">
	<div class="tamanhoConteudo"   style="background:<?php echo Zend_Registry::get('backgroundBlocoImob'); ?>;">
		<!-- Titulo -->
        <div class="tituloPadraoInterna" style="color:<?php echo Zend_Registry::get('colorTxtTituloPadrao'); ?>;">
			<i class="fa fa-chevron-right"></i><span class="tituloPadraoInterna" style="color:<?php echo Zend_Registry::get('colorTxtTituloPadrao'); ?>;">Servi&ccedil;os</span></div>
		<!-- Fim Titulo -->
        <!-- Descrição Empresa -->
        <p class="descricaoTxtInt" style="color:<?php echo Zend_Registry::get('colorTxtInternas'); ?>;"><span class="descricaoTxtInt" style="color:<?php echo Zend_Registry::get('colorTxtInternas'); ?>;">
Em rela&ccedil;&atilde;o aos fatores que interferem no valor de um im&oacute;vel, al&eacute;m da lei da oferta e da procura, as propor&ccedil;&otilde;es, o aproveitamento e a localiza&ccedil;&atilde;o do im&oacute;vel tamb&eacute;m fazem parte desses fatores. A garantia de um neg&oacute;cio seguro e perfeito depende de uma s&eacute;rie de documentos que devem estar devidamente registrados e regularizados, entre, pode-se citar: t&iacute;tulo de propriedade, certid&atilde;o de filia&ccedil;&atilde;o de dom&iacute;nio pelo prazo de 20 anos, certid&atilde;o negativa de &ocirc;nus pelo prazo de 20 anos, repetindo os nomes dos propriet&aacute;rios, da mesma forma que na certid&atilde;o de filia&ccedil;&atilde;o de dom&iacute;nio, etc.<br />
            <br />
O Registro de Im&oacute;veis &eacute; uma tarefa que &eacute; competida ao Oficial de Registro de Im&oacute;veis, que &eacute; o respons&aacute;vel pelo registro, averba&ccedil;&atilde;o e matr&iacute;cula do im&oacute;vel. Todo este processo aplicado sobre a compra de um im&oacute;vel, deve-se principalmente pelo fato de que, como determina o C&oacute;digo Civil, existe uma s&eacute;rie proibi&ccedil;&otilde;es de vendas de im&oacute;veis, bem como de restri&ccedil;&otilde;es para compradores. </span></p>
        <!-- Fim Descrição Empresa -->

    </div>
    <?php echo $this->render('parceiros.phtml');?>
</div>    